### ISSUE TITLE
Ability to disable flash message

### ISSUE THREAD

**Issue by heaven** [Houdini/two_factor_authentication#132]
There's no way to hide this message "Two factor authentication successful."

**Comment by skiningham** [comment]
Each of the locale files in `config\locales` contains a `success` key. Set the message to an empty string, and no message will appear. For example in `en.yml`:

```yaml
en:
  devise:
    two_factor_authentication:
      success: ""
      attempt_failed: "Attempt failed."
      max_login_attempts_reached: "Access completely denied as you have reached your attempts limit"
      contact_administrator: "Please contact your system administrator."
      code_has_been_sent: "Your authentication code has been sent."
```
